<?php
declare(strict_types=1);

/** @var Renderer $this */

use Henrik\View\Renderer;

?>

<!-- footer -->
<footer class="bg-dark">
    <div class="container">
        <div class="row gutter-sm-1">
            <div class="col-12 col-md-2">
                <a href=""><img src="<?php echo $this->asset('images/logo-white.svg')?>" alt="Logo"></a>
            </div>
            <div class="col-12 col-md-6 text-white">
                <p class="mb-4">Generated by Documentor</p>
            </div>
        </div>
    </div>
</footer>
<!-- / footer -->


<script src="<?php echo $this->asset('js/vendor.min.js')?>"  type="application/javascript"></script>
<script src="<?php echo $this->asset('js/app.js')?>"  type="application/javascript"></script>
